# Generated by Django 4.2.7 on 2023-11-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colchon',
            fields=[
                ('numero_colchon', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre_estudiante', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=10)),
                ('residencia', models.PositiveIntegerField()),
                ('colchon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.colchon')),
            ],
        ),
        migrations.AddField(
            model_name='colchon',
            name='lugar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.lugar'),
        ),
    ]
