# Generated by Django 4.2.8 on 2023-12-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_colchon_boton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='municipio',
        ),
    ]
