# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 524)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QLabel{\n"
"    \n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(0, 255, 127);\n"
"    color: rgb(52, 0, 39);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(0, 166, 80);\n"
"\n"
"}\n"
"QFrame{\n"
"background-color: rgb(0, 111, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setGeometry(QtCore.QRect(90, 120, 61, 16))
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 61, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(90, 180, 61, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(90, 210, 61, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(90, 240, 61, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 270, 61, 16))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(90, 300, 61, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(90, 330, 61, 16))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(90, 360, 61, 16))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(90, 390, 61, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(90, 420, 61, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(90, 450, 61, 16))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(20, 150, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 180, 47, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(20, 210, 47, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(20, 240, 47, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(20, 270, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(20, 300, 47, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(20, 330, 47, 21))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(20, 360, 47, 13))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setGeometry(QtCore.QRect(20, 390, 47, 13))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(20, 420, 47, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(20, 450, 47, 13))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label_26.setObjectName("label_26")
        self.line_n = QtWidgets.QLineEdit(self.frame)
        self.line_n.setGeometry(QtCore.QRect(70, 10, 61, 20))
        self.line_n.setObjectName("line_n")
        self.line_x = QtWidgets.QLineEdit(self.frame)
        self.line_x.setGeometry(QtCore.QRect(70, 40, 61, 20))
        self.line_x.setObjectName("line_x")
        self.btn_siguiente = QtWidgets.QPushButton(self.frame)
        self.btn_siguiente.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.btn_siguiente.setObjectName("btn_siguiente")
        self.btn_resultado = QtWidgets.QPushButton(self.frame)
        self.btn_resultado.setGeometry(QtCore.QRect(100, 80, 75, 23))
        self.btn_resultado.setObjectName("btn_resultado")
        self.btn_grafico = QtWidgets.QPushButton(self.frame)
        self.btn_grafico.setGeometry(QtCore.QRect(440, 80, 75, 23))
        self.btn_grafico.setObjectName("btn_grafico")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trabajo de estadistica"))
        self.label_13.setText(_translate("MainWindow", "x"))
        self.label_14.setText(_translate("MainWindow", "x^2"))
        self.label_15.setText(_translate("MainWindow", "y"))
        self.label_16.setText(_translate("MainWindow", "y^2"))
        self.label_17.setText(_translate("MainWindow", "x*y"))
        self.label_18.setText(_translate("MainWindow", "Sxx"))
        self.label_19.setText(_translate("MainWindow", "Sxy"))
        self.label_20.setText(_translate("MainWindow", "Syy"))
        self.label_21.setText(_translate("MainWindow", "b"))
        self.label_22.setText(_translate("MainWindow", "a"))
        self.label_23.setText(_translate("MainWindow", "^y"))
        self.label_24.setText(_translate("MainWindow", "SCR"))
        self.label_25.setText(_translate("MainWindow", "n"))
        self.label_26.setText(_translate("MainWindow", "x"))
        self.btn_siguiente.setText(_translate("MainWindow", "Siguiente"))
        self.btn_resultado.setText(_translate("MainWindow", "Resultado"))
        self.btn_grafico.setText(_translate("MainWindow", "Grafico"))
